#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=1
while [ $i -le 10 ]
do
  if [ $i -eq 10 ]
  then
    echo "Hi"
    ((i++))
  else
    echo "Best School"
    ((i++))
  fi
done
echo "Best School"