#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

count=1

echo "Hour: 0"
while [ $count -le 59 ]; do
  echo $count
  ((count++))
done

counter=1

echo "Hour: 1"
while [ $counter -le 12 ]; do
  echo $counter
  ((counter++))
done  